ALTER TABLE {PREFIX}authors  ADD description TEXT NULL DEFAULT NULL;
ALTER TABLE {PREFIX}authors  ADD image VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE {PREFIX}authors  ADD mailimage VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE {PREFIX}authors ADD xmlimage VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE {PREFIX}category  ADD mailimage VARCHAR(255) NULL DEFAULT NULL;  
ALTER TABLE {PREFIX}category ADD xmlimage VARCHAR(255) NULL DEFAULT NULL;
